~VERSION INFORMATION
VERS.  2.0 : CWLS LOG ASCII STANDARD - VERSION 2.0
WRAP.  NO  : ONE LINE PER DEPTH STEP
~WELL INFORMATION
STRT.M   100.0 : START DEPTH
STOP.M   101.0 : STOP DEPTH
STEP.M     0.5 : STEP
NULL.  -999.25 : NULL VALUE
WELL.  EMPTY_DATA : WELL NAME
~CURVE INFORMATION
DEPT.M : DEPTH
GR  .GAPI : GAMMA RAY
~A
